#!/usr/bin/env node 

'use strict';

var c = require("skilstak-colors");       

//function printPlain() {
//  console.log(c.clear + c.x + "Hello, World");
// }

var printPlain = function (message) {
  console.log(c.clear + c.x + "Hello" + message);
}

var printRed = function (message) {
  console.log(c.clear + c.x + c.red +"Hello" + message);
}

var printRandom = function (message) {
   console.log(c.clear + c.x + c.rc + "Hello" + message);
}

var printMulti = function (message) {
  console.log(c.clear + c.multi("Hello" + message));
}

var name = process.argv[2];

printPlain(name);
printRed(name);
printRandom(name);
printMulti(name)
