#!/usr/bin/env node 

'use strict';

var c = require("skilstak-colors");       

//function printPlain() {
//  console.log(c.clear + c.x + "Hello, World");
// }

var printPlain = function (message) {
  console.log(c.clear + c.x + "Hello" + message);
}

var printRed = function (message) {
  console.log(c.clear + c.x + c.red +"Hello" + message);
}

var printRandom = function (message) {
   console.log(c.clear + c.x + c.rc + "Hello" + message);
}

var printMulti = function (message) {
  console.log(c.clear + c.multi("Hello" + message));
}

var firstValue = process.argv[2];
var name = "World";
var option = "-m";

if (firstValue[0] === "-") {
  option = firstValue;
  console.log("Hello world"  + option)
}
if (option === "-r") {
  printRandom(name);
}
  
printPlain(name);
printRed(name);
printRandom(name);
printMulti(name)
