#!/usr/bin/env python3
if __name__ == '__main__':
    """Not you grans hello world"""

    import hello

    name, option = hello.parse_args()
    message = "Hello, " + name + "!"

    try:
        if option == "-c":
            hello.print_color(message)
        elif option == "-m":
            hello.print_multi(message)
        else:
            hello.print_plain(message)
    except KeyboardInterrupt:
        exit(0)
