#!/usr/bin/env python3

"""Not you grans hello world"""

import skilstak.colors as c
import time
import hello

p = hello.parse_args()
message = "Hello, " + p["who"] + "!"

try:
    if p["option"] == "-c":
        hello.print_color(message)
    elif p["option"] == "-m":
        hello.print_multi(message)
    else:
        hello.print_plain(message)
except KeyboardInterrupt:
    exit(0)
